# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import time
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 400)
        self.pi = QtWidgets.QPushButton(Form)
        self.pi.setGeometry(QtCore.QRect(0, 240, 35, 41))
        self.pi.setAutoFillBackground(False)
        self.pi.setStyleSheet("background-color:green;font-size:12pt;font-weight:bold;color:white;")
        self.pi.setObjectName("pi")
        self.e = QtWidgets.QPushButton(Form)
        self.e.setGeometry(QtCore.QRect(40, 240, 35, 41))
        self.e.setStyleSheet("background-color:green;font-size:12pt;font-weight:bold;color:white;")
        self.e.setObjectName("e")
        self.deg = QtWidgets.QPushButton(Form)
        self.deg.setGeometry(QtCore.QRect(80, 240, 35, 41))
        self.deg.setStyleSheet("background-color:blue;")
        self.deg.setText("")
        self.deg.setObjectName("deg")
        self.fact = QtWidgets.QPushButton(Form)
        self.fact.setGeometry(QtCore.QRect(120, 240, 35, 41))
        self.fact.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.fact.setObjectName("fact")
        self.seven = QtWidgets.QPushButton(Form)
        self.seven.setGeometry(QtCore.QRect(160, 240, 35, 41))
        self.seven.setStyleSheet("font-size:12pt;font-weight:bold")
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(Form)
        self.eight.setGeometry(QtCore.QRect(200, 240, 35, 41))
        self.eight.setStyleSheet("font-size:12pt;font-weight:bold")
        self.eight.setObjectName("eight")
        self.div = QtWidgets.QPushButton(Form)
        self.div.setGeometry(QtCore.QRect(280, 240, 35, 41))
        self.div.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.div.setObjectName("div")
        self.nine = QtWidgets.QPushButton(Form)
        self.nine.setGeometry(QtCore.QRect(240, 240, 35, 41))
        self.nine.setStyleSheet("font-size:12pt;font-weight:bold")
        self.nine.setObjectName("nine")
        self.lBrace = QtWidgets.QPushButton(Form)
        self.lBrace.setGeometry(QtCore.QRect(360, 240, 35, 41))
        self.lBrace.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.lBrace.setObjectName("lBrace")
        self.rBrace = QtWidgets.QPushButton(Form)
        self.rBrace.setGeometry(QtCore.QRect(320, 240, 35, 41))
        self.rBrace.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.rBrace.setObjectName("rBrace")
        self.mul = QtWidgets.QPushButton(Form)
        self.mul.setGeometry(QtCore.QRect(280, 280, 35, 41))
        self.mul.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.mul.setObjectName("mul")
        self.six = QtWidgets.QPushButton(Form)
        self.six.setGeometry(QtCore.QRect(240, 280, 35, 41))
        self.six.setStyleSheet("font-size:12pt;font-weight:bold")
        self.six.setObjectName("six")
        self.ra = QtWidgets.QPushButton(Form)
        self.ra.setGeometry(QtCore.QRect(120, 280, 35, 41))
        self.ra.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.ra.setObjectName("ra")
        self.mod = QtWidgets.QPushButton(Form)
        self.mod.setGeometry(QtCore.QRect(80, 280, 35, 41))
        self.mod.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.mod.setObjectName("mod")
        self.four = QtWidgets.QPushButton(Form)
        self.four.setGeometry(QtCore.QRect(160, 280, 35, 41))
        self.four.setStyleSheet("font-size:12pt;font-weight:bold")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(Form)
        self.five.setGeometry(QtCore.QRect(200, 280, 35, 41))
        self.five.setStyleSheet("font-size:12pt;font-weight:bold")
        self.five.setObjectName("five")
        self.sin = QtWidgets.QPushButton(Form)
        self.sin.setGeometry(QtCore.QRect(0, 280, 75, 41))
        self.sin.setStyleSheet("background-color:green;font-size:12pt;font-weight:bold;color:white;")
        self.sin.setObjectName("sin")
        self.equal = QtWidgets.QPushButton(Form)
        self.equal.setGeometry(QtCore.QRect(320, 280, 75, 41))
        self.equal.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.equal.setObjectName("equal")
        self.sq = QtWidgets.QPushButton(Form)
        self.sq.setGeometry(QtCore.QRect(120, 320, 35, 41))
        self.sq.setStyleSheet("background-color:blue;")
        self.sq.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("root.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sq.setIcon(icon)
        self.sq.setIconSize(QtCore.QSize(20, 20))
        self.sq.setObjectName("sq")
        self.one = QtWidgets.QPushButton(Form)
        self.one.setGeometry(QtCore.QRect(160, 320, 35, 41))
        self.one.setStyleSheet("font-size:12pt;font-weight:bold")
        self.one.setObjectName("one")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 320, 35, 41))
        self.pushButton_21.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.three = QtWidgets.QPushButton(Form)
        self.three.setGeometry(QtCore.QRect(240, 320, 35, 41))
        self.three.setStyleSheet("font-size:12pt;font-weight:bold")
        self.three.setObjectName("three")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(320, 320, 75, 41))
        self.back.setStyleSheet("background-color:red;font-size:12pt;font-weight:bold;color:white;")
        self.back.setObjectName("back")
        self.minus = QtWidgets.QPushButton(Form)
        self.minus.setGeometry(QtCore.QRect(280, 320, 35, 41))
        self.minus.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.minus.setObjectName("minus")
        self.two = QtWidgets.QPushButton(Form)
        self.two.setGeometry(QtCore.QRect(200, 320, 35, 41))
        self.two.setStyleSheet("font-size:12pt;font-weight:bold")
        self.two.setObjectName("two")
        self.cos = QtWidgets.QPushButton(Form)
        self.cos.setGeometry(QtCore.QRect(0, 320, 75, 41))
        self.cos.setStyleSheet("background-color:green;font-size:12pt;font-weight:bold;color:white;")
        self.cos.setObjectName("cos")
        self.loge = QtWidgets.QPushButton(Form)
        self.loge.setGeometry(QtCore.QRect(120, 360, 35, 41))
        self.loge.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.loge.setObjectName("loge")
        self.zero = QtWidgets.QPushButton(Form)
        self.zero.setGeometry(QtCore.QRect(160, 360, 35, 41))
        self.zero.setStyleSheet("font-size:12pt;font-weight:bold")
        self.zero.setObjectName("zero")
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setGeometry(QtCore.QRect(80, 360, 35, 41))
        self.pushButton_29.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.pushButton_29.setObjectName("pushButton_29")
        self.dec = QtWidgets.QPushButton(Form)
        self.dec.setGeometry(QtCore.QRect(240, 360, 35, 41))
        self.dec.setStyleSheet("font-size:12pt;font-weight:bold")
        self.dec.setObjectName("dec")
        self.enter = QtWidgets.QPushButton(Form)
        self.enter.setGeometry(QtCore.QRect(320, 360, 75, 41))
        self.enter.setStyleSheet("background-color:red;font-size:12pt;font-weight:bold;color:white;")
        self.enter.setIconSize(QtCore.QSize(60, 60))
        self.enter.setObjectName("enter")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(280, 360, 35, 41))
        self.add.setStyleSheet("background-color:gray;font-size:12pt;font-weight:bold;color:white;")
        self.add.setObjectName("add")
        self.deg3 = QtWidgets.QPushButton(Form)
        self.deg3.setGeometry(QtCore.QRect(200, 360, 35, 41))
        self.deg3.setStyleSheet("font-size:12pt;font-weight:bold")
        self.deg3.setObjectName("deg3")
        self.tan = QtWidgets.QPushButton(Form)
        self.tan.setGeometry(QtCore.QRect(0, 360, 75, 41))
        self.tan.setStyleSheet("background-color:green;font-size:12pt;font-weight:bold;color:white;")
        self.tan.setObjectName("tan")
        self.ws = QtWidgets.QFrame(Form)
        self.ws.setGeometry(QtCore.QRect(0, 0, 401, 241))
        self.ws.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ws.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ws.setObjectName("ws")
        self.entry = QtWidgets.QLineEdit(self.ws)
        self.entry.setGeometry(QtCore.QRect(0, 0, 361, 31))
        self.entry.setStyleSheet("font-size:14pt;font-weight:bold;")
        self.entry.setReadOnly(False)
        self.entry.setObjectName("entry")
        self.line = QtWidgets.QFrame(self.ws)
        self.line.setGeometry(QtCore.QRect(3, 26, 350, 2))
        self.line.setStyleSheet("background-color:blue")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.cancel = QtWidgets.QPushButton(self.ws)
        self.cancel.setGeometry(QtCore.QRect(360, -1, 41, 32))
        self.cancel.setStyleSheet("background-color:red;font-size:12pt;color:white;font-weight:bold")
        self.cancel.setObjectName("cancel")
        self.label = QtWidgets.QLabel(self.ws)
        self.label.setGeometry(QtCore.QRect(0, 30, 391, 201))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("back.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 282, 15, 21))
        self.label_2.setStyleSheet("background-color:blue;font-size:12pt;font-weight:bold;color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(93, 250, 16, 16))
        self.label_3.setStyleSheet("color:white;font-weight:bold")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "my Calc"))
        self.pi.setText(_translate("Form", "π"))
        self.e.setText(_translate("Form", "e"))
        self.fact.setText(_translate("Form", "n!"))
        self.seven.setText(_translate("Form", "7"))
        self.eight.setText(_translate("Form", "8"))
        self.div.setText(_translate("Form", "/"))
        self.nine.setText(_translate("Form", "9"))
        self.lBrace.setText(_translate("Form", ")"))
        self.rBrace.setText(_translate("Form", "("))
        self.mul.setText(_translate("Form", "*"))
        self.six.setText(_translate("Form", "6"))
        self.ra.setText(_translate("Form", "X "))
        self.mod.setText(_translate("Form", "|X|"))
        self.four.setText(_translate("Form", "4"))
        self.five.setText(_translate("Form", "5"))
        self.sin.setText(_translate("Form", "sin"))
        self.equal.setText(_translate("Form", "="))
        self.one.setText(_translate("Form", "1"))
        self.pushButton_21.setText(_translate("Form", "e^x"))
        self.three.setText(_translate("Form", "3"))
        self.back.setText(_translate("Form", "<-"))
        self.minus.setText(_translate("Form", "-"))
        self.two.setText(_translate("Form", "2"))
        self.cos.setText(_translate("Form", "cos"))
        self.loge.setText(_translate("Form", "ln"))
        self.zero.setText(_translate("Form", "0"))
        self.pushButton_29.setText(_translate("Form", "j"))
        self.dec.setText(_translate("Form", "."))
        self.enter.setText(_translate("Form", "NEW"))
        self.add.setText(_translate("Form", "+"))
        self.deg3.setText(_translate("Form", "S"))
        self.tan.setText(_translate("Form", "tan"))
        self.cancel.setText(_translate("Form", "C"))
        self.label_2.setText(_translate("Form", "Y"))
        self.label_3.setText(_translate("Form", "o"))

class QPushButtonn(QPushButton):
    def __init__(self,parent=None):
        super(QPushButtonn,self).__init__(parent)
        self.ti=0
    def mousePressEvent(self, event):
        self.ti=time.time()
    def mouseReleaseEvent(self, event):
        if time.time()-self.ti>500:
            pass
